export const WALLET_CONNECTED = "WALLET_CONNECTED";
export const DISCONNECT_WALLET = "DISCONNECT_WALLET";
export const SET_WALLET_NETWORK = "SET_WALLET_NETWORK";
export const SET_WALLET_USEADDR = "SET_WALLET_USEADDR";
export const SET_WALLET_REWARDADDR = "SET_WALLET_REWARDADDR";
export const SET_WALLET_BALANCE = "SET_WALLET_BALANCE";
export const SET_WALLET_CONTRACT_BALANCE = "SET_WALLET_CONTRACT_BALANCE";
export const SET_WALLET_ACCOUNT = "SET_WALLET_ACCOUNT";
export const SET_WALLET_LOADING = "SET_WALLET_LOADING";
export const SET_WALLET_ASSETS = "SET_WALLET_ASSETS";
export const SET_WALLET_DATA = "SET_WALLET_DATA";
export const SET_INVALID_CHAIN = "SET_INVALID_CHAIN";
export const ADD_WALLET_ASSET = "ADD_WALLET_ASSET";

export const WALLET_STATE = {
  CONNECTING: "CONNECTING",
  AWAITING_SIGNATURE: "AWAITING_SIGNATURE",
  NO_WALLETS: "NO_WALLETS",
};
